/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package guis;
import dbmodel.DB;
import entity.*;
import hms.HospitalManagementSystem;
import java.awt.Font;
import java.io.File;
import java.io.FileNotFoundException;
import java.sql.SQLException;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.filechooser.*;
import javax.swing.table.*;
/**
 *
 * @author Raiyan
 */
public class Admin extends javax.swing.JFrame {

    /**
     * Creates new form Admin
     */
    private HospitalManagementSystem hms;
    private DB db;
    int listAllType;
    ArrayList<DoctorEntity> docentities = null;
    ArrayList<EmployeeEntity> empentities = null;
    ArrayList<AdministratorEntity> adentities = null;
    public Admin() {
        initComponents();
    }

    public Admin(HospitalManagementSystem hm) {
        initComponents();
        this.setIconImage(new ImageIcon(getClass().getResource("hospital-logo-small.jpg")).getImage());
        hms = hm;
        db = hms.getDB();
        listAll.setFont(new Font("Tahoma", Font.PLAIN, 18));
        listAll.setRowHeight(listAll.getRowHeight()+15);
        listAll.getColumnModel().getColumn(1).setPreferredWidth(listAll.getWidth()/3);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        infoDialogue = new javax.swing.JDialog();
        jScrollPane6 = new javax.swing.JScrollPane();
        infoField = new javax.swing.JTextArea();
        btnPrint = new javax.swing.JButton();
        btnDclose = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        inFname = new javax.swing.JTextField();
        inLname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        inFather = new javax.swing.JTextField();
        inPhone = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        inEmail = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        inAddress = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        upPhoto = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        typeCombo = new javax.swing.JComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        inAcademic = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        btnCreate = new javax.swing.JButton();
        photoPath = new javax.swing.JTextField();
        btnReset = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        searchType = new javax.swing.JComboBox();
        btnAllList = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        detailsField = new javax.swing.JTextArea();
        hintAll = new javax.swing.JTextField();
        imageLabel = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        listAll = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        inID = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        textDes = new javax.swing.JTextArea();
        textDesg = new javax.swing.JTextField();
        btnAssign = new javax.swing.JButton();
        chkDoc = new javax.swing.JCheckBox();
        chkEmp = new javax.swing.JCheckBox();
        imagePane = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        msgAdmin = new javax.swing.JLabel();

        infoDialogue.setTitle("Profile Info");
        infoDialogue.setMinimumSize(new java.awt.Dimension(440, 450));
        infoDialogue.setModal(true);

        infoField.setEditable(false);
        infoField.setColumns(20);
        infoField.setFont(new java.awt.Font("Arial Unicode MS", 0, 16)); // NOI18N
        infoField.setRows(5);
        jScrollPane6.setViewportView(infoField);

        btnPrint.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnPrint.setText("Print");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });

        btnDclose.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnDclose.setText("Close");
        btnDclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDcloseActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Confidential");

        javax.swing.GroupLayout infoDialogueLayout = new javax.swing.GroupLayout(infoDialogue.getContentPane());
        infoDialogue.getContentPane().setLayout(infoDialogueLayout);
        infoDialogueLayout.setHorizontalGroup(
            infoDialogueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoDialogueLayout.createSequentialGroup()
                .addGroup(infoDialogueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(infoDialogueLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(infoDialogueLayout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(btnPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(btnDclose, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(infoDialogueLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        infoDialogueLayout.setVerticalGroup(
            infoDialogueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoDialogueLayout.createSequentialGroup()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(infoDialogueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPrint, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDclose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        inFname.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        inLname.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setText("First Name:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel7.setText("Last Name:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setText("Father's Name:");

        inFather.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        inPhone.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel4.setText("Phone No: ");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel5.setText("E-mail: ");

        inEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        inAddress.setColumns(20);
        inAddress.setFont(new java.awt.Font("Monospaced", 0, 16)); // NOI18N
        inAddress.setRows(5);
        jScrollPane1.setViewportView(inAddress);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel6.setText("Present Address: ");

        upPhoto.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        upPhoto.setText("Upload Photo..");
        upPhoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upPhotoActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Profile Type");

        typeCombo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        typeCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Doctor", "Employee", "Administrator" }));

        inAcademic.setColumns(20);
        inAcademic.setFont(new java.awt.Font("Monospaced", 0, 16)); // NOI18N
        inAcademic.setRows(5);
        jScrollPane2.setViewportView(inAcademic);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Academic Background");

        btnCreate.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnCreate.setText("Create");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        photoPath.setEditable(false);

        btnReset.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel12.setText("128 X 128 px");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(364, 364, 364)
                .addComponent(btnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(104, 104, 104)
                .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(287, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(inPhone)
                            .addComponent(inEmail)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                            .addComponent(inFather, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(inLname, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(inFname, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(97, 97, 97)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(upPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(photoPath, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(typeCombo, javax.swing.GroupLayout.Alignment.LEADING, 0, 140, Short.MAX_VALUE))
                            .addGap(77, 77, 77)))
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addGap(78, 78, 78))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(upPhoto, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(photoPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(typeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 68, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inFname, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inLname, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(inFather, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addGap(53, 53, 53)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(89, 89, 89))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(25, 25, 25)
                            .addComponent(jScrollPane1))))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        jTabbedPane1.addTab("Profile Creation", jPanel2);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 995, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 531, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Leave Management", jPanel4);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 995, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 531, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Patient Release", jPanel5);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Profile Type");

        searchType.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        searchType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Doctor", "Employee", "Administrator", "Patient" }));

        btnAllList.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnAllList.setText("View list");
        btnAllList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAllListActionPerformed(evt);
            }
        });

        detailsField.setColumns(20);
        detailsField.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        detailsField.setRows(5);
        jScrollPane4.setViewportView(detailsField);

        hintAll.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        hintAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hintAllActionPerformed(evt);
            }
        });

        listAll.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        listAll.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Phone No/ ID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        listAll.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listAll.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                listAllKeyPressed(evt);
            }
        });
        jScrollPane7.setViewportView(listAll);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(searchType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(hintAll, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane7))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAllList)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(searchType, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAllList, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hintAll, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(53, 53, 53))
        );

        jTabbedPane1.addTab("View List", jPanel1);

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel19.setText("Phone No: ");

        inID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btnSearch.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        textDes.setEditable(false);
        textDes.setColumns(20);
        textDes.setRows(5);
        jScrollPane5.setViewportView(textDes);

        textDesg.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        textDesg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textDesgActionPerformed(evt);
            }
        });

        btnAssign.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnAssign.setText("Assign");
        btnAssign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignActionPerformed(evt);
            }
        });

        chkDoc.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        chkDoc.setText("Doctor");

        chkEmp.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        chkEmp.setText("Employee");
        chkEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkEmpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(221, 221, 221)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkDoc)
                    .addComponent(chkEmp))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane5)
                    .addComponent(inID, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(textDesg, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(btnAssign, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(imagePane, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inID, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(chkDoc)
                        .addGap(18, 18, 18)
                        .addComponent(chkEmp)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(imagePane, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(textDesg, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(btnAssign, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE))
                        .addGap(84, 84, 84))))
        );

        jTabbedPane1.addTab("Designation Assignment", jPanel3);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Hospital Management System");

        msgAdmin.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        msgAdmin.setForeground(new java.awt.Color(0, 51, 204));
        msgAdmin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 866, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addComponent(msgAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 612, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(msgAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setSize(new java.awt.Dimension(1016, 738));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void textDesgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textDesgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textDesgActionPerformed

    JFileChooser pupload;
    
    private void upPhotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upPhotoActionPerformed
        // TODO add your handling code here:
        FileFilter filter = new FileNameExtensionFilter("Image files _","jpeg","png","gif","jpg","bmp");
        pupload = new JFileChooser("C:/");
        pupload.addChoosableFileFilter(filter);
        int retVal = pupload.showOpenDialog(null);
        
        if(retVal == JFileChooser.APPROVE_OPTION) {
            File imgFile = pupload.getSelectedFile();
            photoPath.setText(imgFile.getAbsolutePath());
        }
    }//GEN-LAST:event_upPhotoActionPerformed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPrintActionPerformed

    private void btnDcloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDcloseActionPerformed
        // TODO add your handling code here:
        infoDialogue.setVisible(false);
    }//GEN-LAST:event_btnDcloseActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
        int type = typeCombo.getSelectedIndex();
        if(type == 0) {
            DoctorEntity doctor = new DoctorEntity(inFname.getText(),inLname.getText(),inFather.getText(),
                                inEmail.getText(),inAddress.getText(),inAcademic.getText(),Integer.parseInt(inPhone.getText()),
                                pupload.getSelectedFile());
            doctor.generateKeys();
            try {
                if(db.addDoctor(doctor)) {
                    msgAdmin.setText("Information is saved successfully.");
                    infoField.setText(doctor.generateSummary());
                    infoDialogue.setVisible(true);
                }
            } catch (SQLException ex) {
                ex.printStackTrace();
                msgAdmin.setText("Database error occured during saving information!");;
            } catch (FileNotFoundException ex) {
                msgAdmin.setText("Error! Image file not found");
            }
        } else if(type == 1) {
            EmployeeEntity employee = new EmployeeEntity(inFname.getText(),inLname.getText(),inFather.getText(),
                                inEmail.getText(),inAddress.getText(),inAcademic.getText(),Integer.parseInt(inPhone.getText()),
                                pupload.getSelectedFile());
            employee.generatePassword();
            try {
                if(db.addEmployee(employee)) {
                    msgAdmin.setText("Information is saved successfully.");
                    infoField.setText(employee.generateSummary());
                    infoDialogue.setVisible(true);
                }
            } catch (SQLException ex) {
                ex.printStackTrace();
                msgAdmin.setText("Database error occured during saving information!");;
            } catch (FileNotFoundException ex) {
                msgAdmin.setText("Error! Image file not found");
            }
        } else if(type == 2) {
            AdministratorEntity admin = new AdministratorEntity(inFname.getText(),inLname.getText(),inFather.getText(),
                                inEmail.getText(),inAddress.getText(),inAcademic.getText(),Integer.parseInt(inPhone.getText()),
                                pupload.getSelectedFile());
            admin.generateKeys();
            try {
                if(db.addAdmin(admin)) {
                    msgAdmin.setText("Information is saved successfully.");
                    infoField.setText(admin.generateSummary());
                    infoDialogue.setVisible(true);
                }
            } catch (SQLException ex) {
                ex.printStackTrace();
                msgAdmin.setText("Database error occured during saving information!");;
            } catch (FileNotFoundException ex) {
                msgAdmin.setText("Error! Image file not found");
            }
        }
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        inFname.setText(null);
        inLname.setText(null);
        inFather.setText(null);
        inEmail.setText(null);
        inAddress.setText(null);
        inAcademic.setText(null);
        inPhone.setText(null);
        if(pupload != null)
            pupload.setSelectedFile(null);
        photoPath.setText(null);
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnAllListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAllListActionPerformed
        // TODO add your handling code here:
        listAllType = searchType.getSelectedIndex();
        DefaultTableModel model;
        model = (DefaultTableModel)listAll.getModel();
        model.setRowCount(0);
        if(hintAll.getText().trim().equals("")) {
            if(listAllType == 0) {
                try {
                    docentities = db.findDoctors();
                    for(DoctorEntity entity : docentities) {
                        //String str = String.format("%-50s0%d", entity.fname+"  "+entity.lname, entity.phone_no);
                        //System.out.println(str);
                        model.addRow(new Object[] {entity.fname+"  "+entity.lname, entity.phone_no});
                    }
                    //listAll.setModel(model);
                } catch (SQLException ex) {
                    msgAdmin.setText("Unable to find information. Database error!");
                }
                if(listAll.getSelectedRow()>=0) {
                    msgAdmin.setText("row selected");
                }
                
            } else if(listAllType == 1) {
                try {
                    empentities = db.findEmployees();
                    for(EmployeeEntity entity : empentities) {
                        //String str = String.format("%-50s0%d", entity.fname+"  "+entity.lname, entity.phone_no);
                        //System.out.println(str);
                        model.addRow(new Object[] {entity.fname+"  "+entity.lname, entity.phone_no});
                    }
                    //listAll.setModel(model);
                } catch (SQLException ex) {
                    msgAdmin.setText("Unable to find information. Database error!");
                }
                if(listAll.getSelectedRow()>=0) {
                    msgAdmin.setText("row selected");
                }

            } else if(listAllType == 2) {
                try {
                    adentities = db.findAdmins();
                    for(AdministratorEntity entity : adentities) {
                        //String str = String.format("%-50s0%d", entity.fname+"  "+entity.lname, entity.phone_no);
                        //System.out.println(str);
                        model.addRow(new Object[] {entity.fname+"  "+entity.lname, entity.phone_no});
                    }
                    //listAll.setModel(model);
                } catch (SQLException ex) {
                    msgAdmin.setText("Unable to find information. Database error!");
                }

            } else if(listAllType == 3) {

            }
        }
    }//GEN-LAST:event_btnAllListActionPerformed

    private void hintAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hintAllActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hintAllActionPerformed

    private void listAllKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_listAllKeyPressed
        // TODO add your handling code here:
        int row;
        if(evt.getKeyChar() == '\n') {
            //msgAdmin.setText("row selected");
            if(listAllType == 0) {
                row = listAll.getSelectedRow();
                if(row>=0) {
                    DoctorEntity doc = docentities.get(row);
                    detailsField.setText("\tProfile Information\n\n");
                    detailsField.append("Email: "+doc.email+"\nAddress:\n"+ doc.address+"\nAcademic Description\n"+doc.academic+"\n");
                    ImageIcon image = new ImageIcon(doc.image);
                    
                    imageLabel.setIcon(image);
                } else {
                    msgAdmin.setText("No profile selected!");
                }
            } else if(listAllType == 1) {
                row = listAll.getSelectedRow();
                if(row>=0) {
                    EmployeeEntity emp = empentities.get(row);
                    detailsField.setText("\tProfile Information\n\n");
                    detailsField.append("Email: "+emp.email+"\nAddress:\n"+ emp.address+"\nAcademic Description\n"+emp.academic+"\n");
                    ImageIcon image = new ImageIcon(emp.image);
                    
                    imageLabel.setIcon(image);
                } else {
                    msgAdmin.setText("No profile selected!");
                }

            } else if(listAllType == 2) {
                row = listAll.getSelectedRow();
                if(row>=0) {
                    AdministratorEntity ad = adentities.get(row);
                    detailsField.setText("\tProfile Information\n\n");
                    detailsField.append("Email: "+ad.email+"\nAddress:\n"+ ad.address+"\nAcademic Description\n"+ad.academic+"\n");
                    ImageIcon image = new ImageIcon(ad.image);
                    
                    imageLabel.setIcon(image);
                } else {
                    msgAdmin.setText("No profile selected!");
                }

            } else if(listAllType == 3) {

            }
        }
    }//GEN-LAST:event_listAllKeyPressed

    private void chkEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkEmpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkEmpActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        DoctorEntity doc = null;
        EmployeeEntity emp = null;
        textDes.setText(null);
        textDesg.setText(null);
        imagePane.setIcon(null);
        if(!chkDoc.isSelected() && !chkEmp.isSelected()) {
            msgAdmin.setText("Sorry!! Please choose one from the checkbox.");
        } else if(chkDoc.isSelected() && chkEmp.isSelected()) {
            msgAdmin.setText("Sorry!! Please choose one from the checkbox. Not both.");
        } else {
            int id=0;
            if(chkDoc.isSelected()) {
                try {
                    id = Integer.parseInt(inID.getText());
                } catch(Exception e) {
                    msgAdmin.setText("Enter number for ID");
                }
                try { 
                    doc = db.docDesg(id);
                } catch (SQLException ex) {
                    msgAdmin.setText("Invalid query. Please try again.");
                }
                if(doc == null) {
                    msgAdmin.setText("No profile matches your query. Try again.");
                } else {
                    textDes.setText("\tProfile Information\n\n");
                    textDes.append("Name: "+ doc.fname+" "+doc.lname+"\n\nEmail: "+doc.email+"\nAddress:\n"+ doc.address+"\nAcademic Description\n"+doc.academic+"\n");
                    if(doc.designation == null) {
                        textDesg.setText("<<No designation assigned.>>");
                    } else {
                        textDesg.setText(doc.designation);
                    }
                    ImageIcon image = new ImageIcon(doc.image);
                    imagePane.setIcon(image);
                }    
            } else if(chkEmp.isSelected()) {
                try {
                    id = Integer.parseInt(inID.getText());
                } catch(Exception e) {
                    msgAdmin.setText("Enter number for ID");
                }
                try { 
                    emp = db.empDesg(id);
                } catch (SQLException ex) {
                    msgAdmin.setText("Invalid query. Please try again.");
                }
                if(emp == null) {
                    msgAdmin.setText("No profile matches your query. Try again.");
                } else {
                    textDes.setText("\tProfile Information\n\n");
                    textDes.append("Name: "+ emp.fname+" "+emp.lname+"\n\nEmail: "+emp.email+"\nAddress:\n"+ emp.address+"\nAcademic Description\n"+emp.academic+"\n");
                    if(emp.designation == null) {
                        textDesg.setText("<<No designation assigned.>>");
                    } else {
                        textDesg.setText(emp.designation);
                    }
                    ImageIcon image = new ImageIcon(emp.image);
                    imagePane.setIcon(image);
                }
            }
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnAssignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignActionPerformed
        // TODO add your handling code here:
        int id;
        String desg;
        id = Integer.parseInt(inID.getText());
        desg = textDesg.getText();
        if(chkDoc.isSelected()) {
            
            try {
                if(db.chgDocDesg(id,desg)) {
                    msgAdmin.setText("Designation changed successfully.");
                } else {
                    msgAdmin.setText("Error occured during saving information.");
                }
            } catch (SQLException ex) {
                msgAdmin.setText("Database error occured.");
            }
        } else if(chkEmp.isSelected()) {
            try {
                if(db.chgEmpDesg(id,desg)) {
                    msgAdmin.setText("Designation changed successfully.");
                } else {
                    msgAdmin.setText("Error occured during saving information.");
                }
            } catch (SQLException ex) {
                msgAdmin.setText("Database error occured.");
            }
        }
    }//GEN-LAST:event_btnAssignActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAllList;
    private javax.swing.JButton btnAssign;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnDclose;
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSearch;
    private javax.swing.JCheckBox chkDoc;
    private javax.swing.JCheckBox chkEmp;
    private javax.swing.JTextArea detailsField;
    private javax.swing.JTextField hintAll;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JLabel imagePane;
    private javax.swing.JTextArea inAcademic;
    private javax.swing.JTextArea inAddress;
    private javax.swing.JTextField inEmail;
    private javax.swing.JTextField inFather;
    private javax.swing.JTextField inFname;
    private javax.swing.JTextField inID;
    private javax.swing.JTextField inLname;
    private javax.swing.JTextField inPhone;
    private javax.swing.JDialog infoDialogue;
    private javax.swing.JTextArea infoField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable listAll;
    private javax.swing.JLabel msgAdmin;
    private javax.swing.JTextField photoPath;
    private javax.swing.JComboBox searchType;
    private javax.swing.JTextArea textDes;
    private javax.swing.JTextField textDesg;
    private javax.swing.JComboBox typeCombo;
    private javax.swing.JButton upPhoto;
    // End of variables declaration//GEN-END:variables
}
